### ISSUE TITLE
parallel mode broken in Linux

### ISSUE THREAD

**Issue by loganmc10** [ata4/angrylion-rdp-plus#44]
In Windows, selecting the "Parallel" option works (mupen64plus). In Linux, the application freezes and must be force closed.

**Comment by ata4** [comment]
Hm, that one might be difficult to debug for me... I'll see what I can do about it.

**Comment by loganmc10** [comment]
I got around to bisecting this, it looks like the bad commit is eef64660d59054daf10504ba5c3af612ee5a2cdd (but actually I tested 5cbd52ee8a213fecdd289337e614b3abdff30990, since it's needed to compile, but I assume the problem is in eef64660d59054daf10504ba5c3af612ee5a2cdd )

I had to remove the "build" folder in between testing commits or else my bisecting would get messed up (it would work when it shouldn't etc...)

Anyway so basically d1cb99f2c0dd01423c6d6b33b9bfc00266b0c03e is the last commit that worked for me

**Comment by Jj0YzL5nvJ** [comment]
In my case the application freezes is random in the start, I can't reproduce it with 100% certain.
But I've noticed that it's easier to get all working when firefox is closed.

**Comment by ata4** [comment]
As far as I can tell, the renderer itself is fine, since the retracer runs stable and fast with parallel rendering enabled on my Ubuntu BM. I'll need to check the M64P plugin interface next.

**Comment by ata4** [comment]
Oh, never mind my previous reply, I forgot to run the retracer with the `-p` flag. It was actually a deadlock issue during the initialization in parallel.cpp, because the constructor didn't wait for the threads to reach a mutex before running tasks. It should be fixed now.

**Comment by Jj0YzL5nvJ** [comment]
I can still reproduce this problem, 1/30 attempts. Is very random.

**Comment by ata4** [comment]
Haven't been able to reproduce so far. But I'll reopen it in case anyone else knows more.

**Comment by loganmc10** [comment]
I haven't had any issues since you closed this

**Comment by ata4** [comment]
I have found two more (silly) mistakes that could have been responsible for the crashes and some abnormalities caused by d52d94f.

**Comment by loganmc10** [comment]
Can this be closed then? Seems stable to me

**Comment by ata4** [comment]
Yeah, I hope it is now.

**Comment by Jj0YzL5nvJ** [comment]
Finally, I can no longer reproduce this issue.
